image: "scorpil/rust:nightly"

before_script:
    - rustc --version
    - cargo --version

build:vk_1_0_12:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_12

build:vk_1_0_11:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_11

build:vk_1_0_10:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_10

build:vk_1_0_9:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_9

build:vk_1_0_8:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_8

build:vk_1_0_7:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_7

build:vk_1_0_6:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_6

build:vk_1_0_5:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_5

build:vk_1_0_4:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_4

build:vk_1_0_3:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_3
