image: "scorpil/rust:nightly"

before_script:
    - rustc --version
    - cargo --version

build:vk_1_0_21:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_21

build:vk_1_0_20:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_20

build:vk_1_0_19:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_19

build:vk_1_0_18:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_18

build:vk_1_0_17:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_17

build:vk_1_0_16:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_16

build:vk_1_0_15:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_15

build:vk_1_0_14:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_14

build:vk_1_0_13:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_13

build:vk_1_0_12:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_12

build:vk_1_0_11:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_11

build:vk_1_0_10:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_10

build:vk_1_0_9:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_9

build:vk_1_0_8:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_8

build:vk_1_0_7:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_7

build:vk_1_0_6:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_6

build:vk_1_0_5:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_5

build:vk_1_0_4:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_4

build:vk_1_0_3:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release --no-default-features --features vk_1_0_3
